# Compose File Reference: https://docs.docker.com/compose/compose-file/
version: '3.7'

services:
    # Docker Image: https://hub.docker.com/r/vinelab/nginx-php
    app:
        build:
            context: .
        ports:
            - ${DOCKER_HOST_APP_PORT:-8000}:80
        volumes:
            - ./:/code:cached
        environment:
            - XDEBUG_CONFIG=remote_host=host.docker.internal

    # Docker Image: https://hub.docker.com/_/neo4j
    neo4j:
        environment:
            - NEO4J_AUTH=none
        image: neo4j:4.4
        ports:
            - ${DOCKER_HOST_NEO4J_HTTP_PORT:-7474}:7474
            - ${DOCKER_HOST_NEO4J_BOLT_PORT:-7687}:7687

