version: '3.7'
networks:
    neo-eloquent:

services:
    app:
        build:
            context: .
        ports:
            - ${DOCKER_HOST_APP_PORT:-8000}:80
        volumes:
            - ./:/opt/project
        environment:
            - NEO4J_HOST=neo4j
            - NEO4J_DATABASE=neo4j
            - NEO4J_PORT=7687
            - NEO4J_USER=neo4j
            - NEO4J_PASSWORD=testtest
        working_dir: /opt/project
        networks:
            - neo-eloquent

    neo4j:
        environment:
            - NEO4J_AUTH=neo4j/testtest
        image: neo4j:5
        ports:
            - ${DOCKER_HOST_NEO4J_HTTP_PORT:-7474}:7474
            - ${DOCKER_HOST_NEO4J_BOLT_PORT:-7687}:7687
        networks:
            - neo-eloquent

