<?php

namespace Vinelab\NeoEloquent\Query;

class Builder extends \Illuminate\Database\Query\Builder
{
    public function get($columns = ['*'])
    {
        return parent::get($columns); // TODO: Change the autogenerated stub
    }
}
